version: "2.2"
services:
# Darkflame LEGO Universe server
# Database
  darkflameserver-db:
    image: mariadb
    container_name: darkflameserver-db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql_darkflame_password
    volumes:
      -  ${MY_DATABASE_FOLDER}:/var/lib/mysql
    networks:
      darkflameserver-net:
    ports:
      - 3306:3306/tcp

# Server
  darkflameserver:
    build:
      context: .
    container_name: darkflameserver
    restart: unless-stopped
    tty: true
    stop_grace_period: 2m
    depends_on:
      - darkflameserver-db
    environment:
      MYSQL_HOST: darkflameserver-db
      MYSQL_DATABASE: luniserver_net
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: mysql_darkflame_password
    volumes:
      -  ${MY_CONFIG_FOLDER}:/config
    networks:
      darkflameserver-net:
    ports:
      - 1001:1001/udp
      - 2000-2200:2000-2200/udp
      - 3000-3200:3000-3200/udp
    
  
  # Accountmanager
  darkflameaccountmanager:
    build:
      context: ./AccountManager
    container_name: darkflameserver-accountmanage
    depends_on:
      - darkflameserver-db
    ports:
      - 5000:5000/tcp 
    networks:
      darkflameserver-net:

networks:
  darkflameserver-net:
    driver: bridge